(define (problem zeno-0) (:domain zeno-travel)
(:customization
(= :time-format "%d/%m/%Y %H:%M:%S")
(= :time-horizon-relative 2500)
(= :time-start "05/06/2007 08:00:00")
(= :time-unit :hours))

(:objects
    p1 p2 p3 p4 p5 p6 p7 p8 p9 p10 p11 p12 p13 p14 p15 p16 p17 p18 p19 p20 - person
    Almeria Barcelona Bilbao Cadiz Cordoba Gibraltar Granada Huelva Jaen Madrid Malaga Sevilla - city
    a1 a2 a3 a4 a5 a6 a7 a8 a9 a10 - aircraft
)
(:init
    (at p1 Madrid) (destino p1 Barcelona)
    (at p2 Madrid) (destino p2 Granada)
    (at p3 Madrid) (destino p3 Gibraltar)
    (at p4 Cadiz) (destino p4 Cordoba)
    (at p5 Barcelona) (destino p5 Bilbao)
    (at p6 Barcelona) (destino p6 Jaen)
    (at p7 Granada) (destino p7 Malaga)
    (at p8 Granada) (destino p8 Madrid)
    (at p9 Granada) (destino p9 Madrid)
    (at p10 Bilbao) (destino p10 Cadiz)
    (at p11 Cordoba) (destino p11 Gibraltar)
    (at p12 Cordoba) (destino p12 Gibraltar)
    (at p13 Cordoba) (destino p13 Granada)
    (at p14 Jaen) (destino p14 Madrid)
    (at p15 Jaen) (destino p15 Sevilla)
    (at p16 Sevilla) (destino p16 Almeria)
    (at p17 Sevilla) (destino p17 Malaga)
    (at p18 Gibraltar) (destino p18 Madrid)
    (at p19 Huelva) (destino p19 Cadiz)
    (at p20 Almeria) (destino p20 Barcelona)

    (= (distance Almeria Almeria) 0)
    (= (distance Almeria Barcelona) 809)
    (= (distance Almeria Bilbao) 958)
    (= (distance Almeria Cadiz) 463)
    (= (distance Almeria Cordoba) 316)
    (= (distance Almeria Gibraltar) 339)
    (= (distance Almeria Granada) 162)
    (= (distance Almeria Huelva) 505)
    (= (distance Almeria Jaen) 220)
    (= (distance Almeria Madrid) 547)
    (= (distance Almeria Malaga) 207)
    (= (distance Almeria Sevilla) 410)

    (= (distance Barcelona Almeria) 809)
    (= (distance Barcelona Barcelona) 0)
    (= (distance Barcelona Bilbao) 620)
    (= (distance Barcelona Cadiz) 1284)
    (= (distance Barcelona Cordoba) 908)
    (= (distance Barcelona Gibraltar) 1124)
    (= (distance Barcelona Granada) 868)
    (= (distance Barcelona Huelva) 1140)
    (= (distance Barcelona Jaen) 804)
    (= (distance Barcelona Madrid) 621)
    (= (distance Barcelona Malaga) 997)
    (= (distance Barcelona Sevilla) 1046)

    (= (distance Bilbao Almeria) 958)
    (= (distance Bilbao Barcelona) 620)
    (= (distance Bilbao Bilbao) 0)
    (= (distance Bilbao Cadiz) 1058)
    (= (distance Bilbao Cordoba) 796)
    (= (distance Bilbao Gibraltar) 1110)
    (= (distance Bilbao Granada) 829)
    (= (distance Bilbao Huelva) 939)
    (= (distance Bilbao Jaen) 730)
    (= (distance Bilbao Madrid) 395)
    (= (distance Bilbao Malaga) 939)
    (= (distance Bilbao Sevilla) 933)

    (= (distance Cadiz Almeria) 463)
    (= (distance Cadiz Barcelona) 1284)
    (= (distance Cadiz Bilbao) 1058)
    (= (distance Cadiz Cadiz) 0)
    (= (distance Cadiz Cordoba) 261)
    (= (distance Cadiz Gibraltar) 124)
    (= (distance Cadiz Granada) 296)
    (= (distance Cadiz Huelva) 214)
    (= (distance Cadiz Jaen) 330)
    (= (distance Cadiz Madrid) 654)
    (= (distance Cadiz Malaga) 240)
    (= (distance Cadiz Sevilla) 126)

    (= (distance Cordoba Almeria) 316)
    (= (distance Cordoba Barcelona) 908)
    (= (distance Cordoba Bilbao) 796)
    (= (distance Cordoba Cadiz) 261)
    (= (distance Cordoba Cordoba) 0)
    (= (distance Cordoba Gibraltar) 294)
    (= (distance Cordoba Granada) 160)
    (= (distance Cordoba Huelva) 241)
    (= (distance Cordoba Jaen) 108)
    (= (distance Cordoba Madrid) 396)
    (= (distance Cordoba Malaga) 165)
    (= (distance Cordoba Sevilla) 143)

    (= (distance Gibraltar Almeria) 339)
    (= (distance Gibraltar Barcelona) 1124)
    (= (distance Gibraltar Bilbao) 1110)
    (= (distance Gibraltar Cadiz) 124)
    (= (distance Gibraltar Cordoba) 294)
    (= (distance Gibraltar Gibraltar) 0)
    (= (distance Gibraltar Granada) 255)
    (= (distance Gibraltar Huelva) 289)
    (= (distance Gibraltar Jaen) 335)
    (= (distance Gibraltar Madrid) 662)
    (= (distance Gibraltar Malaga) 134)
    (= (distance Gibraltar Sevilla) 201)

    (= (distance Granada Almeria) 162)
    (= (distance Granada Barcelona) 868)
    (= (distance Granada Bilbao) 829)
    (= (distance Granada Cadiz) 296)
    (= (distance Granada Cordoba) 160)
    (= (distance Granada Gibraltar) 255)
    (= (distance Granada Granada) 0)
    (= (distance Granada Huelva) 346)
    (= (distance Granada Jaen) 93)
    (= (distance Granada Madrid) 421)
    (= (distance Granada Malaga) 125)
    (= (distance Granada Sevilla) 252)

    (= (distance Huelva Almeria) 505)
    (= (distance Huelva Barcelona) 1140)
    (= (distance Huelva Bilbao) 939)
    (= (distance Huelva Cadiz) 214)
    (= (distance Huelva Cordoba) 241)
    (= (distance Huelva Gibraltar) 289)
    (= (distance Huelva Granada) 346)
    (= (distance Huelva Huelva) 0)
    (= (distance Huelva Jaen) 347)
    (= (distance Huelva Madrid) 591)
    (= (distance Huelva Malaga) 301)
    (= (distance Huelva Sevilla) 95)

    (= (distance Jaen Almeria) 220)
    (= (distance Jaen Barcelona) 804)
    (= (distance Jaen Bilbao) 730)
    (= (distance Jaen Cadiz) 330)
    (= (distance Jaen Cordoba) 108)
    (= (distance Jaen Gibraltar) 335)
    (= (distance Jaen Granada) 93)
    (= (distance Jaen Huelva) 347)
    (= (distance Jaen Jaen) 0)
    (= (distance Jaen Madrid) 335)
    (= (distance Jaen Malaga) 203)
    (= (distance Jaen Sevilla) 246)

    (= (distance Madrid Almeria) 547)
    (= (distance Madrid Barcelona) 621)
    (= (distance Madrid Bilbao) 395)
    (= (distance Madrid Cadiz) 654)
    (= (distance Madrid Cordoba) 396)
    (= (distance Madrid Gibraltar) 662)
    (= (distance Madrid Granada) 421)
    (= (distance Madrid Huelva) 591)
    (= (distance Madrid Jaen) 335)
    (= (distance Madrid Madrid) 0)
    (= (distance Madrid Malaga) 532)
    (= (distance Madrid Sevilla) 534)

    (= (distance Malaga Almeria) 207)
    (= (distance Malaga Barcelona) 997)
    (= (distance Malaga Bilbao) 939)
    (= (distance Malaga Cadiz) 240)
    (= (distance Malaga Cordoba) 165)
    (= (distance Malaga Gibraltar) 134)
    (= (distance Malaga Granada) 125)
    (= (distance Malaga Huelva) 301)
    (= (distance Malaga Jaen) 203)
    (= (distance Malaga Madrid) 532)
    (= (distance Malaga Malaga) 0)
    (= (distance Malaga Sevilla) 209)

    (= (distance Sevilla Almeria) 410)
    (= (distance Sevilla Barcelona) 1046)
    (= (distance Sevilla Bilbao) 933)
    (= (distance Sevilla Cadiz) 126)
    (= (distance Sevilla Cordoba) 143)
    (= (distance Sevilla Gibraltar) 201)
    (= (distance Sevilla Granada) 252)
    (= (distance Sevilla Huelva) 95)
    (= (distance Sevilla Jaen) 246)
    (= (distance Sevilla Madrid) 534)
    (= (distance Sevilla Malaga) 209)
    (= (distance Sevilla Sevilla) 0)


    (= (boarding-time) 0)
    (= (debarking-time) 0)


    (at a1 Madrid)
    (= (fuel a1) 2000)
    (= (slow-speed a1) 100)
    (= (fast-speed a1) 200)
    (= (slow-burn a1) 1)
    (= (fast-burn a1) 2)
    (= (capacity a1) 2000)
    (= (refuel-rate a1) 10)
    (= (total-fuel-used a1) 0)
    (= (fuel-limit a1) 39880)
    (= (passengers-aboard a1) 0)
    (= (max-passengers a1) 20)
    (= (max-duration a1) 4)

    (at a2 Barcelona)
    (= (fuel a2) 2600)
    (= (slow-speed a2) 150)
    (= (fast-speed a2) 300)
    (= (slow-burn a2) 1)
    (= (fast-burn a2) 2)
    (= (capacity a2) 2600)
    (= (refuel-rate a2) 10)
    (= (total-fuel-used a2) 0)
    (= (fuel-limit a2) 51360)
    (= (passengers-aboard a2) 0)
    (= (max-passengers a2) 20)
    (= (max-duration a2) 3)

    (at a3 Granada)
    (= (fuel a3) 2500)
    (= (slow-speed a3) 100)
    (= (fast-speed a3) 200)
    (= (slow-burn a3) 1)
    (= (fast-burn a3) 2)
    (= (capacity a3) 2500)
    (= (refuel-rate a3) 10)
    (= (total-fuel-used a3) 0)
    (= (fuel-limit a3) 34720)
    (= (passengers-aboard a3) 0)
    (= (max-passengers a3) 20)
    (= (max-duration a3) 3)

    (at a4 Sevilla)
    (= (fuel a4) 2200)
    (= (slow-speed a4) 80)
    (= (fast-speed a4) 160)
    (= (slow-burn a4) 1)
    (= (fast-burn a4) 2)
    (= (capacity a4) 2200)
    (= (refuel-rate a4) 10)
    (= (total-fuel-used a4) 0)
    (= (fuel-limit a4) 41840)
    (= (passengers-aboard a4) 0)
    (= (max-passengers a4) 20)
    (= (max-duration a4) 3)

    (at a5 Bilbao)
    (= (fuel a5) 2220)
    (= (slow-speed a5) 120)
    (= (fast-speed a5) 240)
    (= (slow-burn a5) 1)
    (= (fast-burn a5) 2)
    (= (capacity a5) 2220)
    (= (refuel-rate a5) 10)
    (= (total-fuel-used a5) 0)
    (= (fuel-limit a5) 44400)
    (= (passengers-aboard a5) 0)
    (= (max-passengers a5) 20)
    (= (max-duration a5) 3)

    (at a6 Jaen)
    (= (fuel a6) 2000)
    (= (slow-speed a6) 100)
    (= (fast-speed a6) 200)
    (= (slow-burn a6) 1)
    (= (fast-burn a6) 2)
    (= (capacity a6) 2000)
    (= (refuel-rate a6) 10)
    (= (total-fuel-used a6) 0)
    (= (fuel-limit a6) 32160)
    (= (passengers-aboard a6) 0)
    (= (max-passengers a6) 20)
    (= (max-duration a6) 3)

    (at a7 Cordoba)
    (= (fuel a7) 2000)
    (= (slow-speed a7) 100)
    (= (fast-speed a7) 200)
    (= (slow-burn a7) 1)
    (= (fast-burn a7) 2)
    (= (capacity a7) 2000)
    (= (refuel-rate a7) 10)
    (= (total-fuel-used a7) 0)
    (= (fuel-limit a7) 36320)
    (= (passengers-aboard a7) 0)
    (= (max-passengers a7) 20)
    (= (max-duration a7) 3)

    (at a8 Gibraltar)
    (= (fuel a8) 2500)
    (= (slow-speed a8) 200)
    (= (fast-speed a8) 300)
    (= (slow-burn a8) 1)
    (= (fast-burn a8) 2)
    (= (capacity a8) 2500)
    (= (refuel-rate a8) 10)
    (= (total-fuel-used a8) 0)
    (= (fuel-limit a8) 44960)
    (= (passengers-aboard a8) 0)
    (= (max-passengers a8) 20)
    (= (max-duration a8) 4)

    (at a9 Cadiz)
    (= (fuel a9) 2600)
    (= (slow-speed a9) 100)
    (= (fast-speed a9) 200)
    (= (slow-burn a9) 1)
    (= (fast-burn a9) 2)
    (= (capacity a9) 2600)
    (= (refuel-rate a9) 10)
    (= (total-fuel-used a9) 0)
    (= (fuel-limit a9) 51360)
    (= (passengers-aboard a9) 0)
    (= (max-passengers a9) 20)
    (= (max-duration a9) 4)

    (at a10 Almeria)
    (= (fuel a10) 2500)
    (= (slow-speed a10) 100)
    (= (fast-speed a10) 200)
    (= (slow-burn a10) 1)
    (= (fast-burn a10) 2)
    (= (capacity a10) 2500)
    (= (refuel-rate a10) 10)
    (= (total-fuel-used a10) 0)
    (= (fuel-limit a10) 40000)
    (= (passengers-aboard a10) 0)
    (= (max-passengers a10) 20)
    (= (max-duration a10) 4)
 )


(:tasks-goal
   :tasks(
   (transport-person p1 Barcelona)
   (transport-person p2 Granada)
   (transport-person p3 Gibraltar)
   (transport-person p4 Cordoba)
   (transport-person p5 Bilbao)
   (transport-person p6 Jaen)
   (transport-person p7 Malaga)
   (transport-person p8 Madrid)
   (transport-person p9 Madrid)
   (transport-person p10 Cadiz)

   (transport-person p11 Gibraltar)
   (transport-person p12 Gibraltar)
   (transport-person p13 Granada)
   (transport-person p14 Madrid)
   (transport-person p15 Sevilla)
   (transport-person p16 Almeria)
   (transport-person p17 Malaga)
   (transport-person p18 Madrid)
   (transport-person p19 Cadiz)
   (transport-person p20 Barcelona)


   )
  )
)
